spring.application.name=api-gateway

server.port=8080

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# Eureka Instance
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

# =========================
# GATEWAY ROUTES
# =========================

# Auth Service Route
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTHSERVICEAPP
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

# Product Service Route
spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=lb://product-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/product/**

# Cart Service Route
spring.cloud.gateway.routes[2].id=cart-service
spring.cloud.gateway.routes[2].uri=lb://cart-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/cart/**

# Order Service Route
spring.cloud.gateway.routes[3].id=order-service
spring.cloud.gateway.routes[3].uri=lb://order-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/order/**


spring.profiles.active=local