# Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/shopcore_cart_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Pratek29082021
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver